FROM mysql:5

ENV MYSQL_ROOT_PASSWORD root
ENV MYSQL_DATABASE products_db
ENV MYSQL_USER mysql
ENV MYSQL_PASSWORD mysql
# when container will be started, we'll have `test` database created with this schema
COPY ./create.sql /docker-entrypoint-initdb.d/