version: '3.8'

services:
  users-db:
    container_name: users-db
    build: ./services/users/src/db
    ports:
      - '5430:5430'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
    healthcheck:
      test: exit 0

  products-db:
    container_name: products-db
    build: ./services/products/src/db
    ports:
      - '5431:5431'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
    healthcheck:
      test: exit 0

  notes-db:
    container_name: notes-db
    build: ./services/notes/src/db
    ports:
      - '5432:5432'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
    healthcheck:
      test: exit 0

  comments-db:
    container_name: comments-db
    build: ./services/comments/src/db
    ports:
      - '5433:5433'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
    healthcheck:
      test: exit 0

  baskets-db:
    container_name: baskets-db
    build: ./services/baskets/src/db
    ports:
      - '5434:5434'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      resources:
        limits:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
    healthcheck:
      test: exit 0

  categories-db:
    container_name: categories-db
    build: ./services/categories/src/db
    ports:
      - '5434:5434'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      resources:
        limits:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
    healthcheck:
      test: exit 0

  authentifications-db:
    container_name: authentifications-db
    build: ./services/authentifications/src/db
    ports:
      - '5435:5435'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      resources:
        limits:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
    healthcheck:
      test: exit 0





  users-service:
    container_name: users-service
    build: ./services/users/
    volumes:
      - './services/users:/usr/src/app'
      - './services/users/package.json:/usr/src/package.json'
    ports:
      - '3000:3000'
    environment:
      - SERVICE_PORT=3000
      - DATABASE_HOST=users-db
      - DATABASE_USER=mysql
      - DATABASE_PW=mysql
      - DATABASE_DB=users_db
    deploy:
      resources:
        limits:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
    depends_on:
      users-db:
        condition: service_healthy

  products-service:
    container_name: products-service
    build: ./services/products/
    volumes:
      - './services/products:/usr/src/app'
      - './services/products/package.json:/usr/src/package.json'
    ports:
      - '3001:3001'
    environment:
      - SERVICE_PORT=3001
      - DATABASE_HOST=products-db
      - DATABASE_USER=mysql
      - DATABASE_PW=mysql
      - DATABASE_DB=products_db
    deploy:
      resources:
        limits:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
    depends_on:
      products-db:
        condition: service_healthy

  notes-service:
    container_name: notes-service
    build: ./services/notes/
    volumes:
      - './services/notes:/usr/src/app'
      - './services/notes/package.json:/usr/src/package.json'
    ports:
      - '3002:3002'
    environment:
      - SERVICE_PORT=3002
      - DATABASE_HOST=notes-db
      - DATABASE_USER=mysql
      - DATABASE_PW=mysql
      - DATABASE_DB=notes_db
    deploy:
      resources:
        limits:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
    depends_on:
      notes-db:
        condition: service_healthy

  comments-service:
    container_name: comments-service
    build: ./services/comments/
    volumes:
      - './services/comments:/usr/src/app'
      - './services/comments/package.json:/usr/src/package.json'
    ports:
      - '3003:3003'
    environment:
      - SERVICE_PORT=3003
      - DATABASE_HOST=comments-db
      - DATABASE_USER=mysql
      - DATABASE_PW=mysql
      - DATABASE_DB=comments_db
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
    depends_on:
      comments-db:
        condition: service_healthy

  categories-service:
    container_name: categories-service
    build: ./services/categories/
    volumes:
      - './services/categories:/usr/src/app'
      - './services/categories/package.json:/usr/src/package.json'
    ports:
      - '3003:3003'
    environment:
      - SERVICE_PORT=3003
      - DATABASE_HOST=categories-db
      - DATABASE_USER=mysql
      - DATABASE_PW=mysql
      - DATABASE_DB=categories_db
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
    depends_on:
      categories-db:
        condition: service_healthy

  baskets-service:
    container_name: baskets-service
    build: ./services/baskets/
    volumes:
      - './services/baskets:/usr/src/app'
      - './services/baskets/package.json:/usr/src/package.json'
    ports:
      - '3004:3004'
    environment:
      - SERVICE_PORT=3004
      - DATABASE_HOST=baskets-db
      - DATABASE_USER=mysql
      - DATABASE_PW=mysql
      - DATABASE_DB=baskets_db
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
    depends_on:
      baskets-db:
        condition: service_healthy

  authentifications-service:
    container_name: authentifications-service
    build: ./services/authentifications/
    volumes:
      - './services/authentifications:/usr/src/app'
      - './services/authentifications/package.json:/usr/src/package.json'
    ports:
      - '3005:3005'
    environment:
      - SERVICE_PORT=3005
      - DATABASE_HOST=authentifications-db
      - DATABASE_USER=mysql
      - DATABASE_PW=mysql
      - DATABASE_DB=authentifications_db
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 128M
        reservations:
          cpus: 0.25
          memory: 64M
    depends_on:
      authentifications-db:
        condition: service_healthy