version: '2.1'

services:

  users-db:
    container_name: users-db
    build: ./app/services/users/src/db
    ports:
      - '5433:5432' # expose ports - HOST:CONTAINER
    environment:
      - SQL_USER=sqluser
      - SQL_PASSWORD=sqlpw
    healthcheck:
      test: exit 0
      
  users-service:
    container_name: users-service
    build: ./services/users/
    volumes:
      - './services/users:/usr/src/app'
      - './services/users/package.json:/usr/src/package.json'
    ports:
      - '3000:3000' # expose ports - HOST:CONTAINER
    environment:
      - DATABASE_URL=mysql://mysql:mysql@users-db:5432/users_dev
      - DATABASE_TEST_URL=mysql://mysql:mysql@users-db:5432/users_test
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=changeme
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db