version: '3.8'

services:
  users-db:
    container_name: users-db
    build: ./app/services/users/src/db
    ports:
      - '5433:5432' # expose ports - HOST:CONTAINER
    restart: always
    environment:
      - DB_USER=sqluser
      - DB_PASSWORD=sqlpw
    healthcheck:
      test: exit 0
      
  users-service:
    container_name: users-service
    build: ./app/services/users/
    volumes:
      - './app/services/users:/usr/src/app'
      - './app/services/users/package.json:/usr/src/package.json'
    ports:
      - '3000:3000' # expose ports - HOST:CONTAINER
    restart: always
    environment:
      - DATABASE_URL=mysql://mysql:mysql@users-db:5432/users_dev
      - DATABASE_TEST_URL=mysql://mysql:mysql@users-db:5432/users_test
      - NODE_ENV=development
      - TOKEN_SECRET=changeme
    depends_on:
      - users-db
    links:
      - users-db